/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2015-01-20 04:44:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.com_alkacon_bootstrap_formatters.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bootstrap_002dgrid_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/opencms.tld", Long.valueOf(1414568902000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005flink;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005flink = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.release();
    _005fjspx_005ftagPool_005fcms_005flink.release();
    _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.release();
    _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody.release();
    _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby.release();
    _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 0, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<title>OpenCms | ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</title>\n");
      out.write("\t\n");
      out.write("\t<meta charset=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.requestContext.encoding}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t\n");
      out.write("\t<meta name=\"description\" content=\"");
      if (_jspx_meth_cms_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("\t<meta name=\"keywords\" content=\"");
      if (_jspx_meth_cms_005fproperty_005f1(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("\t<meta name=\"robots\" content=\"index, follow\">\n");
      out.write("\t<meta name=\"revisit-after\" content=\"7 days\">\n");
      out.write("\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"");
      if (_jspx_meth_cms_005flink_005f0(_jspx_page_context))
        return;
      out.write("\"/>\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"");
      if (_jspx_meth_cms_005flink_005f1(_jspx_page_context))
        return;
      out.write("\" type=\"image/png\"/>\n");
      out.write("\n");
      out.write("\t");
      if (_jspx_meth_cms_005fenable_002dade_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_cms_005flink_005f2(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_cms_005flink_005f3(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\tjQuery(document).ready(function() {\n");
      out.write("\t\t\tApp.init();\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!--[if lt IE 9]>\n");
      out.write("    \t<script src=\"");
      if (_jspx_meth_cms_005flink_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("\t<![endif]-->\n");
      out.write("\t");
      if (_jspx_meth_cms_005finclude_005f0(_jspx_page_context))
        return;
      out.write("</head><body>\n");
      out.write("<div class=\"page-wrap wrapper\">\n");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      if (_jspx_meth_cms_005fcontainer_005f0(_jspx_page_context))
        return;
      out.write("</div><!--/page-wrap-->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(6,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetLocale_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.locale}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:property
    org.opencms.jsp.CmsJspTagProperty _jspx_th_cms_005fproperty_005f0 = (org.opencms.jsp.CmsJspTagProperty) _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.get(org.opencms.jsp.CmsJspTagProperty.class);
    _jspx_th_cms_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fproperty_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(15,35) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f0.setName("Description");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(15,35) name = file type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f0.setFile("search");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(15,35) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f0.setDefault("");
    int _jspx_eval_cms_005fproperty_005f0 = _jspx_th_cms_005fproperty_005f0.doStartTag();
    if (_jspx_th_cms_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005fproperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:property
    org.opencms.jsp.CmsJspTagProperty _jspx_th_cms_005fproperty_005f1 = (org.opencms.jsp.CmsJspTagProperty) _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.get(org.opencms.jsp.CmsJspTagProperty.class);
    _jspx_th_cms_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fproperty_005f1.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(16,32) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f1.setName("Keywords");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(16,32) name = file type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f1.setFile("search");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(16,32) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f1.setDefault("");
    int _jspx_eval_cms_005fproperty_005f1 = _jspx_th_cms_005fproperty_005f1.doStartTag();
    if (_jspx_th_cms_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_cms_005flink_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:link
    org.opencms.jsp.CmsJspTagLink _jspx_th_cms_005flink_005f0 = (org.opencms.jsp.CmsJspTagLink) _005fjspx_005ftagPool_005fcms_005flink.get(org.opencms.jsp.CmsJspTagLink.class);
    _jspx_th_cms_005flink_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005flink_005f0.setParent(null);
    int _jspx_eval_cms_005flink_005f0 = _jspx_th_cms_005flink_005f0.doStartTag();
    if (_jspx_eval_cms_005flink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005flink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005flink_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005flink_005f0.doInitBody();
      }
      do {
        out.write("/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/img/favicon_120.png");
        int evalDoAfterBody = _jspx_th_cms_005flink_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005flink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005flink_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:link
    org.opencms.jsp.CmsJspTagLink _jspx_th_cms_005flink_005f1 = (org.opencms.jsp.CmsJspTagLink) _005fjspx_005ftagPool_005fcms_005flink.get(org.opencms.jsp.CmsJspTagLink.class);
    _jspx_th_cms_005flink_005f1.setPageContext(_jspx_page_context);
    _jspx_th_cms_005flink_005f1.setParent(null);
    int _jspx_eval_cms_005flink_005f1 = _jspx_th_cms_005flink_005f1.doStartTag();
    if (_jspx_eval_cms_005flink_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005flink_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005flink_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005flink_005f1.doInitBody();
      }
      do {
        out.write("/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/img/favicon_16.png");
        int evalDoAfterBody = _jspx_th_cms_005flink_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005flink_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005flink_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f1);
    return false;
  }

  private boolean _jspx_meth_cms_005fenable_002dade_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:enable-ade
    org.opencms.jsp.CmsJspTagEnableAde _jspx_th_cms_005fenable_002dade_005f0 = (org.opencms.jsp.CmsJspTagEnableAde) _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody.get(org.opencms.jsp.CmsJspTagEnableAde.class);
    _jspx_th_cms_005fenable_002dade_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fenable_002dade_005f0.setParent(null);
    int _jspx_eval_cms_005fenable_002dade_005f0 = _jspx_th_cms_005fenable_002dade_005f0.doStartTag();
    if (_jspx_th_cms_005fenable_002dade_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody.reuse(_jspx_th_cms_005fenable_002dade_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fenable_002dade_005fnobody.reuse(_jspx_th_cms_005fenable_002dade_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(25,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not cms.isOnlineProject}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        if (_jspx_meth_cms_005fheadincludes_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005fheadincludes_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:headincludes
    org.opencms.jsp.CmsJspTagHeadIncludes _jspx_th_cms_005fheadincludes_005f0 = (org.opencms.jsp.CmsJspTagHeadIncludes) _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.get(org.opencms.jsp.CmsJspTagHeadIncludes.class);
    _jspx_th_cms_005fheadincludes_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fheadincludes_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(26,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f0.setType("css");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(26,2) name = closetags type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f0.setClosetags("false");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(26,2) name = defaults type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f0.setDefaults("/system/modules/com.alkacon.bootstrap.basics/resources/bootstrap/css/bootstrap.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/style.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/app.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/bxslider/jquery.bxslider.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/line-icons/line-icons.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/font-awesome/css/font-awesome.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/search.css");
    int _jspx_eval_cms_005fheadincludes_005f0 = _jspx_th_cms_005fheadincludes_005f0.doStartTag();
    if (_jspx_th_cms_005fheadincludes_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(34,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.isOnlineProject}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        if (_jspx_meth_cms_005fheadincludes_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_cms_005fheadincludes_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:headincludes
    org.opencms.jsp.CmsJspTagHeadIncludes _jspx_th_cms_005fheadincludes_005f1 = (org.opencms.jsp.CmsJspTagHeadIncludes) _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.get(org.opencms.jsp.CmsJspTagHeadIncludes.class);
    _jspx_th_cms_005fheadincludes_005f1.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fheadincludes_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(35,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f1.setType("css");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(35,2) name = closetags type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f1.setClosetags("false");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(35,2) name = defaults type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f1.setDefaults("/system/modules/com.alkacon.bootstrap.basics/resources/bootstrap/css/bootstrap.min.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/style.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/app.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/bxslider/jquery.bxslider.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/line-icons/line-icons.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/font-awesome/css/font-awesome.css\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/search.css");
    int _jspx_eval_cms_005fheadincludes_005f1 = _jspx_th_cms_005fheadincludes_005f1.doStartTag();
    if (_jspx_th_cms_005fheadincludes_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fclosetags_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(44,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("colortheme");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_c_005fset_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005fset_005f0.doInitBody();
      }
      do {
        if (_jspx_meth_cms_005fproperty_005f2(_jspx_th_c_005fset_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:property
    org.opencms.jsp.CmsJspTagProperty _jspx_th_cms_005fproperty_005f2 = (org.opencms.jsp.CmsJspTagProperty) _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.get(org.opencms.jsp.CmsJspTagProperty.class);
    _jspx_th_cms_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f0);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(44,25) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f2.setName("bs.page.color");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(44,25) name = file type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f2.setFile("search");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(44,25) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f2.setDefault("red");
    int _jspx_eval_cms_005fproperty_005f2 = _jspx_th_cms_005fproperty_005f2.doStartTag();
    if (_jspx_th_cms_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(45,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("pagelayout");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_c_005fset_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005fset_005f1.doInitBody();
      }
      do {
        if (_jspx_meth_cms_005fproperty_005f3(_jspx_th_c_005fset_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fset_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_cms_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:property
    org.opencms.jsp.CmsJspTagProperty _jspx_th_cms_005fproperty_005f3 = (org.opencms.jsp.CmsJspTagProperty) _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.get(org.opencms.jsp.CmsJspTagProperty.class);
    _jspx_th_cms_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f1);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(45,25) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f3.setName("bs.page.layout");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(45,25) name = file type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f3.setFile("search");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(45,25) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fproperty_005f3.setDefault("9");
    int _jspx_eval_cms_005fproperty_005f3 = _jspx_th_cms_005fproperty_005f3.doStartTag();
    if (_jspx_th_cms_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fproperty_0026_005fname_005ffile_005fdefault_005fnobody.reuse(_jspx_th_cms_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_cms_005flink_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:link
    org.opencms.jsp.CmsJspTagLink _jspx_th_cms_005flink_005f2 = (org.opencms.jsp.CmsJspTagLink) _005fjspx_005ftagPool_005fcms_005flink.get(org.opencms.jsp.CmsJspTagLink.class);
    _jspx_th_cms_005flink_005f2.setPageContext(_jspx_page_context);
    _jspx_th_cms_005flink_005f2.setParent(null);
    int _jspx_eval_cms_005flink_005f2 = _jspx_th_cms_005flink_005f2.doStartTag();
    if (_jspx_eval_cms_005flink_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005flink_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005flink_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005flink_005f2.doInitBody();
      }
      do {
        out.write("/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/css/themes/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${colortheme}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(".css");
        int evalDoAfterBody = _jspx_th_cms_005flink_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005flink_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005flink_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f2);
    return false;
  }

  private boolean _jspx_meth_cms_005flink_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:link
    org.opencms.jsp.CmsJspTagLink _jspx_th_cms_005flink_005f3 = (org.opencms.jsp.CmsJspTagLink) _005fjspx_005ftagPool_005fcms_005flink.get(org.opencms.jsp.CmsJspTagLink.class);
    _jspx_th_cms_005flink_005f3.setPageContext(_jspx_page_context);
    _jspx_th_cms_005flink_005f3.setParent(null);
    int _jspx_eval_cms_005flink_005f3 = _jspx_th_cms_005flink_005f3.doStartTag();
    if (_jspx_eval_cms_005flink_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005flink_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005flink_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005flink_005f3.doInitBody();
      }
      do {
        out.write("/system/modules/com.alkacon.bootstrap.formatters/resources/css/page.css");
        int evalDoAfterBody = _jspx_th_cms_005flink_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005flink_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005flink_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(49,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not cms.isOnlineProject}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        if (_jspx_meth_cms_005fheadincludes_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_cms_005fheadincludes_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:headincludes
    org.opencms.jsp.CmsJspTagHeadIncludes _jspx_th_cms_005fheadincludes_005f2 = (org.opencms.jsp.CmsJspTagHeadIncludes) _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.get(org.opencms.jsp.CmsJspTagHeadIncludes.class);
    _jspx_th_cms_005fheadincludes_005f2.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fheadincludes_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(50,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f2.setType("javascript");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(50,2) name = defaults type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f2.setDefaults("/system/modules/com.alkacon.bootstrap.basics/resources/jquery/jquery-1.11.1.js\n		    |/system/modules/com.alkacon.bootstrap.basics/resources/jquery/jquery-migrate-1.2.1.min.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/bootstrap/js/bootstrap.min.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/bxslider/jquery.bxslider.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/back-to-top.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/js/app.js");
    int _jspx_eval_cms_005fheadincludes_005f2 = _jspx_th_cms_005fheadincludes_005f2.doStartTag();
    if (_jspx_th_cms_005fheadincludes_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(57,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.isOnlineProject}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        if (_jspx_meth_cms_005fheadincludes_005f3(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_cms_005fheadincludes_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:headincludes
    org.opencms.jsp.CmsJspTagHeadIncludes _jspx_th_cms_005fheadincludes_005f3 = (org.opencms.jsp.CmsJspTagHeadIncludes) _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.get(org.opencms.jsp.CmsJspTagHeadIncludes.class);
    _jspx_th_cms_005fheadincludes_005f3.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fheadincludes_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(58,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f3.setType("javascript");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(58,2) name = defaults type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fheadincludes_005f3.setDefaults("/system/modules/com.alkacon.bootstrap.basics/resources/jquery/jquery-1.11.1.min.js\n		    |/system/modules/com.alkacon.bootstrap.basics/resources/jquery/jquery-migrate-1.2.1.min.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/bootstrap/js/bootstrap.min.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/bxslider/jquery.bxslider.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/back-to-top.js\n			|/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/js/app.js");
    int _jspx_eval_cms_005fheadincludes_005f3 = _jspx_th_cms_005fheadincludes_005f3.doStartTag();
    if (_jspx_th_cms_005fheadincludes_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fheadincludes_0026_005ftype_005fdefaults_005fnobody.reuse(_jspx_th_cms_005fheadincludes_005f3);
    return false;
  }

  private boolean _jspx_meth_cms_005flink_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:link
    org.opencms.jsp.CmsJspTagLink _jspx_th_cms_005flink_005f4 = (org.opencms.jsp.CmsJspTagLink) _005fjspx_005ftagPool_005fcms_005flink.get(org.opencms.jsp.CmsJspTagLink.class);
    _jspx_th_cms_005flink_005f4.setPageContext(_jspx_page_context);
    _jspx_th_cms_005flink_005f4.setParent(null);
    int _jspx_eval_cms_005flink_005f4 = _jspx_th_cms_005flink_005f4.doStartTag();
    if (_jspx_eval_cms_005flink_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005flink_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005flink_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005flink_005f4.doInitBody();
      }
      do {
        out.write("/system/modules/com.alkacon.bootstrap.basics/resources/theme-unify/plugins/respond.js");
        int evalDoAfterBody = _jspx_th_cms_005flink_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005flink_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005flink_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005flink.reuse(_jspx_th_cms_005flink_005f4);
    return false;
  }

  private boolean _jspx_meth_cms_005finclude_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:include
    org.opencms.jsp.CmsJspTagInclude _jspx_th_cms_005finclude_005f0 = (org.opencms.jsp.CmsJspTagInclude) _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody.get(org.opencms.jsp.CmsJspTagInclude.class);
    _jspx_th_cms_005finclude_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005finclude_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(74,1) name = file type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005finclude_005f0.setFile("/system/modules/com.alkacon.bootstrap.formatters/search/config.jsp");
    int _jspx_eval_cms_005finclude_005f0 = _jspx_th_cms_005finclude_005f0.doStartTag();
    if (_jspx_th_cms_005finclude_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody.reuse(_jspx_th_cms_005finclude_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005finclude_0026_005ffile_005fnobody.reuse(_jspx_th_cms_005finclude_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(77,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cms.isEditMode}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<!--=== Placeholder for OpenCms toolbar in edit mode ===-->\n");
        out.write("<div style=\"background: lightgray; height: 35px\">&nbsp;</div>\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_cms_005fcontainer_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:container
    org.opencms.jsp.CmsJspTagContainer _jspx_th_cms_005fcontainer_005f0 = (org.opencms.jsp.CmsJspTagContainer) _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby.get(org.opencms.jsp.CmsJspTagContainer.class);
    _jspx_th_cms_005fcontainer_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fcontainer_005f0.setParent(null);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(82,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fcontainer_005f0.setName("page-complete");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(82,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fcontainer_005f0.setType("page");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(82,0) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fcontainer_005f0.setWidth("1200");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(82,0) name = maxElements type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fcontainer_005f0.setMaxElements("15");
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(82,0) name = editableby type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fcontainer_005f0.setEditableby("ROLE.DEVELOPER");
    int _jspx_eval_cms_005fcontainer_005f0 = _jspx_th_cms_005fcontainer_005f0.doStartTag();
    if (_jspx_eval_cms_005fcontainer_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005fcontainer_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005fcontainer_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005fcontainer_005f0.doInitBody();
      }
      do {
        if (_jspx_meth_cms_005fbundle_005f0(_jspx_th_cms_005fcontainer_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_cms_005fcontainer_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005fcontainer_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005fcontainer_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby.reuse(_jspx_th_cms_005fcontainer_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fcontainer_0026_005fwidth_005ftype_005fname_005fmaxElements_005feditableby.reuse(_jspx_th_cms_005fcontainer_005f0);
    return false;
  }

  private boolean _jspx_meth_cms_005fbundle_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cms_005fcontainer_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cms:bundle
    org.opencms.jsp.CmsJspTagBundle _jspx_th_cms_005fbundle_005f0 = (org.opencms.jsp.CmsJspTagBundle) _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename.get(org.opencms.jsp.CmsJspTagBundle.class);
    _jspx_th_cms_005fbundle_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cms_005fbundle_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cms_005fcontainer_005f0);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(83,4) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cms_005fbundle_005f0.setBasename("com.alkacon.bootstrap.formatters.messages");
    int _jspx_eval_cms_005fbundle_005f0 = _jspx_th_cms_005fbundle_005f0.doStartTag();
    if (_jspx_eval_cms_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_cms_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_cms_005fbundle_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_cms_005fbundle_005f0.doInitBody();
      }
      do {
        out.write("<div class=\"servive-block rounded-3x servive-block-red\">\n");
        out.write("            <h2 class=\"heading-md\">");
        if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_cms_005fbundle_005f0, _jspx_page_context))
          return true;
        out.write("</h4>\n");
        out.write("            <p>");
        if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_cms_005fbundle_005f0, _jspx_page_context))
          return true;
        out.write("</p>           \n");
        out.write("        </div>\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_cms_005fbundle_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_cms_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_cms_005fbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename.reuse(_jspx_th_cms_005fbundle_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcms_005fbundle_0026_005fbasename.reuse(_jspx_th_cms_005fbundle_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_cms_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cms_005fbundle_005f0);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(85,35) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("bootstrap.page.headline.emptycontainer");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_cms_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_cms_005fbundle_005f0);
    // /WEB-INF/jsp/offline/system/modules/com.alkacon.bootstrap.formatters/templates/bootstrap-grid-page.jsp(86,15) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("bootstrap.page.text.emptycontainer");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }
}
