/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2015-01-20 02:55:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.setup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class step_005f2_005fcheck_005fcomponents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.opencms.setup.CmsSetupBean Bean = null;
      synchronized (session) {
        Bean = (org.opencms.setup.CmsSetupBean) _jspx_page_context.getAttribute("Bean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (Bean == null){
          Bean = new org.opencms.setup.CmsSetupBean();
          _jspx_page_context.setAttribute("Bean", Bean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("Bean"), request);


	// next page
	String nextPage = "step_3_database_selection.jsp";	
	// previous page
	String prevPage = "index.jsp";

	boolean isSubmitted = (request.getParameter("systemInfo") != null);
	boolean hasSystemInfo = (request.getParameter("systemInfo") != null) && (request.getParameter("systemInfo").equals("false"));
	boolean hasUserAccepted = (request.getParameter("accept") != null) && (request.getParameter("accept").equals("true"));

	String descriptions = "";
	org.opencms.setup.comptest.CmsSetupTests setupTests = null;
	org.opencms.setup.comptest.CmsSetupTestResult testResult = null;
	String resultIcon = null;
	String helpIcon = null;
	String violatedConditions = "";
	String questionableConditions = "";

	if (Bean.isInitialized()) {
		if(!isSubmitted) {
			setupTests = new org.opencms.setup.comptest.CmsSetupTests();
			setupTests.runTests(Bean);
		} else {
			response.sendRedirect(nextPage);
		}
	}

      out.write('\n');
      out.print( Bean.getHtmlPart("C_HTML_START") );
      out.write("\n");
      out.write("Alkacon OpenCms Setup Wizard - Component tests\n");
      out.print( Bean.getHtmlPart("C_HEAD_START") );
      out.write('\n');
      out.print( Bean.getHtmlPart("C_STYLES") );
      out.write('\n');
      out.print( Bean.getHtmlPart("C_STYLES_SETUP") );
      out.write('\n');
      out.print( Bean.getHtmlPart("C_SCRIPT_HELP") );
      out.write("\n");
      out.write("<script type=\"text/javascript\" language=\"JavaScript\">\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("function toggleContinueButton() {\n");
      out.write("\tvar form = document.components;\t\n");
      out.write("\tform.submit.disabled = !form.accept.checked;\n");
      out.write("}\n");
      out.write("\n");
      out.write("//-->\n");
      out.write("</script>\n");
      out.print( Bean.getHtmlPart("C_HEAD_END") );
      out.write("\n");
      out.write("Alkacon OpenCms Setup Wizard - Component tests\n");
      out.print( Bean.getHtmlPart("C_CONTENT_SETUP_START") );
      out.write('\n');
 if (Bean.isInitialized()) { 
      out.write("\n");
      out.write("<form action=\"");
      out.print( nextPage );
      out.write("\" method=\"post\" class=\"nomargin\" name=\"components\">\n");
      out.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%; height: 350px;\">\n");
      out.write("<tr>\n");
      out.write("\t<td style=\"vertical-align: top; height: 100%;\">\n");
  
	if (isSubmitted) {
		if (hasSystemInfo && !hasUserAccepted) {
			out.print("<b>To continue the Alkacon OpenCms setup you have to recognize that your system may not work with OpenCms!");
		}
	} else { 	

      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_START", "Component tests") );
      out.write("\t\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%;\"><tr><td>\n");
      out.write("\t\t<div style=\"width: 100%; height:130px; overflow: auto;\">\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"2\">\n");
      out.write("\t\t\n");

		List testResults = setupTests.getTestResults();
		for (int i=0;i<testResults.size();i++) {
			testResult = (org.opencms.setup.comptest.CmsSetupTestResult) testResults.get(i);
			
			if (testResult.isRed()) {
				resultIcon = "cross";
				violatedConditions += "<p>" + testResult.getInfo() + "</p>";
			} else if (testResult.isYellow()) {
				resultIcon = "unknown";
				questionableConditions += "<p>" + testResult.getInfo() + "</p>";
			} else if (testResult.isGreen() && (testResult.getInfo() != null) && !"".equals(testResult.getInfo())) {
				questionableConditions += "<p>" + testResult.getInfo() + "</p>";
				resultIcon = "check";
			} else {
				resultIcon = "check";
			}
					
			if (!testResult.isGreen() && (testResult.getHelp() != null) && !"".equals(testResult.getHelp())) {
				descriptions += Bean.getHtmlPart("C_HELP_START", "" + i) + testResult.getHelp() + Bean.getHtmlPart("C_HELP_END");
				helpIcon = Bean.getHtmlHelpIcon("" + i, "");
			} else {
				helpIcon = "";
			}
			

      out.write("\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"text-align: left; white-space: nowrap;\">");
      out.print( testResult.getName() );
      out.write(":</td>\n");
      out.write("\t\t\t\t<td style=\"text-align: left; font-weight:bold; width: 100%;\">");
      out.print( testResult.getResult() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td style=\"text-align: right; width: 40px; height: 16px; white-space: nowrap;\">");
      out.print( helpIcon );
      out.write("&nbsp;<img src=\"resources/");
      out.print( resultIcon );
      out.write(".png\" border=\"0\"></td>\n");
      out.write("\t\t\t</tr>\n");

		}	

      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</td></tr></table>\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_END") );
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"dialogspacer\" unselectable=\"on\">&nbsp;</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div style=\"width: 100%; height:120px; overflow: auto;\">\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"5\" cellspacing=\"0\">\n");
      out.write("\t\t\t<tr><td align=\"center\" valign=\"top\">\n");
      out.write("\t\t\t");

				if(setupTests.isRed()) {
					out.print("<img src='resources/error.png'>");
				} else if (setupTests.isYellow()) {
					out.print("<img src='resources/warning.png'>");
				} else {
					out.print("<img src='resources/ok.png'>");
				}
			
      out.write("\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td colspan=\"2\" valign=\"middle\">\n");
      out.write("\t\t\t");

				if (setupTests.isRed()) {
					out.println("<p>Your system does not have the necessary components to use Alkacon OpenCms. It is assumed that OpenCms will not run on your system.</p>");
					out.println(violatedConditions);
				} else if (setupTests.isYellow()) {
					out.print("Your system uses components which have not been tested to work with Alkacon OpenCms. It is possible that OpenCms will not run on your system.");
					out.println(questionableConditions);
				} else {
					out.println("<b>Your system uses components which have been tested to work properly with Alkacon OpenCms.</b>");
					if (!"".equals(questionableConditions)) {
					    out.print(" <b>But, please, be sure to check following points:</b>");					    
						out.println(questionableConditions);
					}
				}
			
      out.write("</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"dialogspacer\" unselectable=\"on\">&nbsp;</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"2\" cellspacing=\"0\">\n");
      out.write("\t\t\t");
 if (!setupTests.isGreen()) { 
			    // show table
			
      out.write("\n");
      out.write("\t\t\t\t<tr><td>\n");
      out.write("\t\t\t\t<table border=\"0\"><tr>\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top;\"><input type=\"checkbox\" name=\"accept\" value=\"true\" onClick=\"toggleContinueButton()\"> </td>\n");
      out.write("\t\t\t\t\t<td style=\"padding-top: 5px;\">I have noticed that my system may not have the necessary components to use Alkacon OpenCms. Continue anyway.</td>\n");
      out.write("\t\t\t\t</tr></table>\n");
      out.write("\t\t\t\t</td></tr>\n");
      out.write("\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t\t\t\n");
      out.write("\t\t<input type=\"hidden\" name=\"systemInfo\" value=\"");
      out.print( setupTests.isGreen() );
      out.write("\">\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.print( Bean.getHtmlPart("C_CONTENT_END") );
      out.write('\n');
      out.write('\n');
      out.print( Bean.getHtmlPart("C_BUTTONS_START") );
      out.write("\n");
      out.write("<input name=\"back\" type=\"button\" value=\"&#060;&#060; Back\" class=\"dialogbutton\" onclick=\"location.href='");
      out.print( prevPage );
      out.write("';\">\n");

String disabled = "";
if (!setupTests.isGreen() && !hasUserAccepted) {
	disabled = " disabled=\"disabled\"";
}

      out.write("\n");
      out.write("<input name=\"submit\" type=\"submit\" value=\"Continue &#062;&#062;\" class=\"dialogbutton\"");
      out.print( disabled );
      out.write(">\n");
      out.write("<input name=\"cancel\" type=\"button\" value=\"Cancel\" class=\"dialogbutton\" onclick=\"location.href='index.jsp';\" style=\"margin-left: 50px;\">\n");
      out.write("</form>\n");
      out.print( Bean.getHtmlPart("C_BUTTONS_END") );
      out.write('\n');
      out.write('\n');
      out.print( descriptions );
      out.write('\n');
      out.write('\n');
 } else	{ 
      out.write('\n');
      out.print( Bean.displayError(""));
      out.write('\n');
      out.print( Bean.getHtmlPart("C_CONTENT_END") );
      out.write('\n');
      out.write('\n');
 } 
      out.write('\n');
      out.print( Bean.getHtmlPart("C_HTML_END") );
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
