/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2015-01-20 04:22:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.setup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class step_005f10_005ffinished_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.opencms.setup.CmsSetupBean Bean = null;
      synchronized (session) {
        Bean = (org.opencms.setup.CmsSetupBean) _jspx_page_context.getAttribute("Bean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (Bean == null){
          Bean = new org.opencms.setup.CmsSetupBean();
          _jspx_page_context.setAttribute("Bean", Bean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("Bean"), request);


	String servletMapping = Bean.getServletMapping();
	if (!servletMapping.startsWith("/")) {
	    servletMapping = "/" + servletMapping;
	}
	if (servletMapping.endsWith("/*")) {
	    // usually a mapping must be in the form "/opencms/*", cut off all slashes
	    servletMapping = servletMapping.substring(0, servletMapping.length() - 2);
	}
	String openLink = request.getContextPath() + servletMapping + "/index.html";
	if (Bean.isInitialized()) {
		Bean.prepareStep10();
		session.invalidate();
	}

      out.write('\n');
      out.print( Bean.getHtmlPart("C_HTML_START") );
      out.write("\n");
      out.write("Alkacon OpenCms Setup Wizard\n");
      out.print( Bean.getHtmlPart("C_HEAD_START") );
      out.write('\n');
      out.print( Bean.getHtmlPart("C_STYLES") );
      out.write('\n');
      out.print( Bean.getHtmlPart("C_STYLES_SETUP") );
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function openWin() {\n");
      out.write("\tvar theWindow = window.open(\"");
      out.print( openLink );
      out.write("\", \"OpenCms\", \"top=10,left=10,width=980,height=550,location=yes,menubar=yes,resizable=yes,scrollbars=yes,status=yes,toolbar=yes\");\n");
      out.write("\ttheWindow.focus();\n");
      out.write("}\n");
 if (Bean.isInitialized()) { 
// open window

      out.write("\n");
      out.write("openWin();\n");
 } 
      out.write("\n");
      out.write("</script>\n");
      out.print( Bean.getHtmlPart("C_HEAD_END") );
      out.write("\n");
      out.write("Alkacon OpenCms Setup Wizard - Finished\n");
      out.print( Bean.getHtmlPart("C_CONTENT_SETUP_START") );
      out.write('\n');
 if (Bean.isInitialized()) { 
      out.write("\n");
      out.write("\n");
      out.write("<table border=\"0\" cellpadding=\"5\" cellspacing=\"0\" style=\"width: 100%; height: 100%;\">\n");
      out.write("<tr>\n");
      out.write("\t<td style=\"vertical-align: bottom;\">\n");
      out.write("\t\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_START", "Alkacon OpenCms setup finished") );
      out.write("\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%;\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><img src=\"resources/ok.png\" border=\"0\"></td>\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t<td style=\"width: 100%;\">\t\t\t\t\t\n");
      out.write("\t\t\t\t    The OpenCms welcome page should display in a newly opened browser window now.<br>\n");
      out.write("\t\t\t\t\tIf it does not display, press <a target=\"OpenCms\" href=\"");
      out.print( openLink );
      out.write("\">here</a> to open it.\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_END") );
      out.write("\n");
      out.write("\t\t<div class=\"dialogspacer\" unselectable=\"on\">&nbsp;</div>\n");
      out.write("\t</td>\t\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td style=\"vertical-align: top;\">\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_START", "Wizard locked") );
      out.write("\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%;\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><img src=\"resources/warning.png\" border=\"0\"></td>\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\tThis setup wizard has now been locked.<br>\n");
      out.write("\t\t\t\t\tTo use the wizard again reset the flag in the \"opencms.properties\".\n");
      out.write("\t\t\t\t\tFor security reasons, you should remove the \"/setup\" folder later when\n");
      out.write("\t\t\t\t\tyou have your Alkacon OpenCms installation running.\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t");
      out.print( Bean.getHtmlPart("C_BLOCK_END") );
      out.write("\n");
      out.write("\t</td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.print( Bean.getHtmlPart("C_CONTENT_END") );
      out.write('\n');
      out.write('\n');
      out.print( Bean.getHtmlPart("C_BUTTONS_START") );
      out.write("\n");
      out.write("<form action=\"\" method=\"post\" class=\"nomargin\">\n");
      out.write("<input name=\"back\" type=\"button\" value=\"&#060;&#060; Back\" class=\"dialogbutton\" disabled=\"disabled\">\n");
      out.write("<input name=\"submit\" type=\"button\" value=\"Continue &#062;&#062;\" class=\"dialogbutton\" disabled=\"disabled\">\n");
      out.write("<input name=\"cancel\" type=\"button\" value=\"Cancel\" class=\"dialogbutton\" style=\"margin-left: 50px;\" disabled=\"disabled\">\n");
      out.write("</form>\n");
      out.print( Bean.getHtmlPart("C_BUTTONS_END") );
      out.write('\n');
 } else	{ 
      out.write('\n');
      out.print( Bean.displayError(""));
      out.write('\n');
      out.print( Bean.getHtmlPart("C_CONTENT_END") );
      out.write('\n');
 } 
      out.write('\n');
      out.print( Bean.getHtmlPart("C_HTML_END") );
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
